### ISSUE TITLE
Any way of reuse in non-Vue apps?

### ISSUE THREAD

**Issue by andrew-kuzovov** [neSpecc/telebook#1]
Hi!
Is there some way to reuse styles for React for example?
or only complete manual rewrite?

**Comment by neSpecc** [comment]
You can reuse [theme styles](https://github.com/neSpecc/telebook/tree/main/client/src/presentation/styles/theme) (typography, colors, etc). The component styles are currently integrated with the Vue template, but you should be able to rewrite them for React without much difficulty
